spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/hansol?serverTimezone=Asia/Seoul
    username: root
    password: ${PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true # model프로퍼티 camel case설정

  mapper-locations: mapper/**/*.xml # Mybatis mapper 위치 설정

  type-aliases-package: com.example.project_hansol.domain.member.model # 패키지 result type에 명을 생략할 수 있도록 alias설정